"""Public orchestration API for STNet."""

from __future__ import annotations

import sys as _sys

from .run import launch, predict, train
from ..backend.environment import (
    AdamW,
    AutoCast,
    Distributed,
    DotProductAttention,
    FlopCounter,
    IncrementalPCA,
    LossWeightController,
    Accelerator,
    MultiScaleRetention,
    MultiScaleRetentionCompat,
    Network,
    SDPBackend,
    StandardScaler,
    System,
    TorchCompat,
    VarianceThreshold,
    _to_sdpa_backends,
    attention_flops_bshd,
    datatype,
    dtypes,
    get_device,
    get_runtime_config,
    initialize_sdpa_backends,
    inference,
    is_fake_tensor,
    is_meta_or_fake_tensor,
    is_meta_tensor,
    joining,
    no_synchronization,
    patch_torch,
    postprocess,
    preprocess,
    sdpa_kernel,
)

__all__ = [
    "train",
    "predict",
    "launch",
    "AutoCast",
    "DotProductAttention",
    "MultiScaleRetention",
    "MultiScaleRetentionCompat",
    "AdamW",
    "Accelerator",
    "LossWeightController",
    "attention_flops_bshd",
    "FlopCounter",
    "inference",
    "joining",
    "no_synchronization",
    "Distributed",
    "Network",
    "System",
    "get_device",
    "get_runtime_config",
    "initialize_sdpa_backends",
    "patch_torch",
    "TorchCompat",
    "SDPBackend",
    "sdpa_kernel",
    "_to_sdpa_backends",
    "VarianceThreshold",
    "StandardScaler",
    "IncrementalPCA",
    "preprocess",
    "postprocess",
    "datatype",
    "dtypes",
    "is_fake_tensor",
    "is_meta_tensor",
    "is_meta_or_fake_tensor",
]

_sys.modules[__name__ + ".dtypes"] = datatype
